package com.example.thanhhoa.enums;

public enum Status {
    ACTIVE, INACTIVE, ONSALE, WAITING, PACKAGING, DELIVERING, RECEIVED, APPROVED, DENIED, WORKING,
    STAFFCANCELED, CUSTOMERCANCELED, DONE, SIGNED, NEW
}
