package com.example.thanhhoa.enums;

public enum Status {
    ACTIVE, INACTIVE, ONSALE, WAITING, PACKAGING, DELIVERING, RECEIVED, APPROVED, DENIED, WORKING,
    CUSTOMERCANCELED, STAFFCANCELED, DONE, SIGNED, NEW, SUCCESS, FAIL
}
